//Google Login details actions
export const GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_ERROR = "GOOGLE_SIGN_IN_ERROR";
//Facebook Login details actions
export const FACEBOOK_SIGN_IN_START = "FACEBOOK_SIGN_IN_START";
export const FACEBOOK_SIGN_IN_SUCCESS = "FACEBOOK_SIGN_IN_SUCCESS";
export const FACEBOOK_SIGN_IN_ERROR = "FACEBOOK_SIGN_IN_ERROR";
//Instagram Login details actions
export const INSTAGRAM_SIGN_IN_START = "INSTAGRAM_SIGN_IN_START";
export const INSTAGRAM_SIGN_IN_SUCCESS = "INSTAGRAM_SIGN_IN_SUCCESS";
export const INSTAGRAM_SIGN_IN_ERROR = "INSTAGRAM_SIGN_IN_ERROR";
//Signup details actions
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
//Login using email id details actions
export const LOGIN_USING_EMAILID_START = "LOGIN_USING_EMAILID_START";
export const LOGIN_USING_EMAILID_SUCCESS = "LOGIN_USING_EMAILID_SUCCESS";
export const LOGIN_USING_EMAILID_ERROR = "LOGIN_USING_EMAILID_ERROR";
//Login using mobile number details actions
export const LOGIN_USING_MOBILE_NUMBER_START = "LOGIN_USING_MOBILE_NUMBER_START";
export const LOGIN_USING_MOBILE_NUMBER_SUCCESS = "LOGIN_USING_MOBILE_NUMBER_SUCCESS";
export const LOGIN_USING_MOBILE_NUMBER_ERROR = "LOGIN_USING_MOBILE_NUMBER_ERROR";
//Signup using email id details actions
export const SIGNUP_USING_EMAILID_START = "SIGNUP_USING_EMAILID_START";
export const SIGNUP_USING_EMAILID_SUCCESS = "SIGNUP_USING_EMAILID_SUCCESS";
export const SIGNUP_USING_EMAILID_ERROR = "SIGNUP_USING_EMAILID_ERROR";
//Signup using mobile number details actions
export const SIGNUP_USING_MOBILE_NUMBER_START = "SIGNUP_USING_MOBILE_NUMBER_START";
export const SIGNUP_USING_MOBILE_NUMBER_SUCCESS = "SIGNUP_USING_MOBILE_NUMBER_SUCCESS";
export const SIGNUP_USING_MOBILE_NUMBER_ERROR = "SIGNUP_USING_MOBILE_NUMBER_ERROR";
//Otp verification using email id details actions
export const VERIFY_OTP_USING_EMAILID_START = "VERIFY_OTP_USING_EMAILID_START";
export const VERIFY_OTP_USING_EMAILID_SUCCESS = "VERIFY_OTP_USING_EMAILID_SUCCESS";
export const VERIFY_OTP_USING_EMAILID_ERROR = "VERIFY_OTP_USING_EMAILID_ERROR";
// verifiOTP_cation using mobile number details actions
export const VERIFY_OTP_USING_MOBILE_NUMBER_START = "VERIFY_OTP_USING_MOBILE_NUMBER_START";
export const VERIFY_OTP_USING_MOBILE_NUMBER_SUCCESS = "VERIFY_OTP_USING_MOBILE_NUMBER_SUCCESS";
export const VERIFY_OTP_USING_MOBILE_NUMBER_ERROR = "VERIFY_OTP_USING_MOBILE_NUMBER_ERROR";
// verifiOTP_cation using mobile number details actions
export const VERIFY_OTP_NEW_PASSWORD_START = "VERIFY_OTP_NEW_PASSWORD_START";
export const VERIFY_OTP_NEW_PASSWORD_SUCCESS = "VERIFY_OTP_NEW_PASSWORD_SUCCESS";
export const VERIFY_OTP_NEW_PASSWORD_ERROR = "VERIFY_OTP_NEW_PASSWORD_ERROR";
// resend OTP details actions
export const CREATE_RESEND_OTP_START = "CREATE_RESEND_OTP_START";
export const CREATE_RESEND_OTP_SUCCESS = "CREATE_RESEND_OTP_SUCCESS";
export const CREATE_RESEND_OTP_ERROR = "CREATE_RESEND_OTP_ERROR";
// create password recovery details
export const CREATE_PASSWORD_RECOVERY_START = "CREATE_PASSWORD_RECOVERY_START";
export const CREATE_PASSWORD_RECOVERY_SUCCESS = "CREATE_PASSWORD_RECOVERY_SUCCESS";
export const CREATE_PASSWORD_RECOVERY_ERROR = "CREATE_PASSWORD_RECOVERY_ERROR";

// create new password recovery details
export const CREATE_NEW_PASSWORD_START = "CREATE_NEW_PASSWORD_START";
export const CREATE_NEW_PASSWORD_SUCCESS = "CREATE_NEW_PASSWORD_SUCCESS";
export const CREATE_NEW_PASSWORD_ERROR = "CREATE_NEW_PASSWORD_ERROR";

// update new password recovery details
export const UPDATE_PASSWORD_START = "UPDATE_PASSWORD_START";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";
//Login using email id details actions
export const LOGIN_WITH_EMAILID_START = "LOGIN_WITH_EMAILID_START";
export const LOGIN_WITH_EMAILID_SUCCESS = "LOGIN_WITH_EMAILID_SUCCESS";
export const LOGIN_WITH_EMAILID_ERROR = "LOGIN_WITH_EMAILID_ERROR";
// Login using mobile number details actions
export const LOGIN_WITH_MOBILE_NUMBER_START = "LOGIN_WITH_MOBILE_NUMBER_START";
export const LOGIN_WITH_MOBILE_NUMBER_SUCCESS = "LOGIN_WITH_MOBILE_NUMBER_SUCCESS";
export const LOGIN_WITH_MOBILE_NUMBER_ERROR = "LOGIN_WITH_MOBILE_NUMBER_ERROR";
//create a new user 
export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const LOAD_USER_START = "LOAD_USER_START";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOAD_HOME_CAROUSELDATA_START = "LOAD_HOME_CAROUSELDATA_START";
export const LOAD_HOME_CAROUSELDATA_SUCCESS = "LOAD_HOME_CAROUSELDATA_SUCCESS";
export const LOAD_HOME_CAROUSELDATA_ERROR = "LOAD_HOME_CAROUSELDATA_ERROR";

export const LOAD_HOME_GRAND_GLOBAL_DATA_START = "LOAD_HOME_GRAND_GLOBAL_DATA_START";
export const LOAD_HOME_GRAND_GLOBAL_DATA_SUCCESS = "LOAD_HOME_GRAND_GLOBAL_DATA_SUCCESS";
export const LOAD_HOME_GRAND_GLOBAL_DATA_ERROR = "LOAD_HOME_GRAND_GLOBAL_DATA_ERROR";

export const LOAD_HOME_SHOP_CATEGORY_DATA_START = "LOAD_HOME_SHOP_CATEGORY_DATA_START";
export const LOAD_HOME_SHOP_CATEGORY_DATA_SUCCESS = "LOAD_HOME_SHOP_CATEGORY_DATA_SUCCESS";
export const LOAD_HOME_SHOP_CATEGORY_DATA_ERROR = "LOAD_HOME_SHOP_CATEGORY_DATA_ERROR";


