//Google Login details actions
export const GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_ERROR = "GOOGLE_SIGN_IN_ERROR";
//Facebook Login details actions
export const FACEBOOK_SIGN_IN_START = "FACEBOOK_SIGN_IN_START";
export const FACEBOOK_SIGN_IN_SUCCESS = "FACEBOOK_SIGN_IN_SUCCESS";
export const FACEBOOK_SIGN_IN_ERROR = "FACEBOOK_SIGN_IN_ERROR";
//Instagram Login details actions
export const INSTAGRAM_SIGN_IN_START = "INSTAGRAM_SIGN_IN_START";
export const INSTAGRAM_SIGN_IN_SUCCESS = "INSTAGRAM_SIGN_IN_SUCCESS";
export const INSTAGRAM_SIGN_IN_ERROR = "INSTAGRAM_SIGN_IN_ERROR";
//Signup details actions
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
//Login using email id details actions
export const LOGIN_USING_EMAILID_START = "LOGIN_USING_EMAILID_START";
export const LOGIN_USING_EMAILID_SUCCESS = "LOGIN_USING_EMAILID_SUCCESS";
export const LOGIN_USING_EMAILID_ERROR = "LOGIN_USING_EMAILID_ERROR";
//Login using mobile number details actions
export const LOGIN_USING_MOBILE_NUMBER_START =
  "LOGIN_USING_MOBILE_NUMBER_START";
export const LOGIN_USING_MOBILE_NUMBER_SUCCESS =
  "LOGIN_USING_MOBILE_NUMBER_SUCCESS";
export const LOGIN_USING_MOBILE_NUMBER_ERROR =
  "LOGIN_USING_MOBILE_NUMBER_ERROR";
//Signup using email id details actions
export const SIGNUP_USING_EMAILID_START = "SIGNUP_USING_EMAILID_START";
export const SIGNUP_USING_EMAILID_SUCCESS = "SIGNUP_USING_EMAILID_SUCCESS";
export const SIGNUP_USING_EMAILID_ERROR = "SIGNUP_USING_EMAILID_ERROR";
//Signup using mobile number details actions
export const SIGNUP_USING_MOBILE_NUMBER_START =
  "SIGNUP_USING_MOBILE_NUMBER_START";
export const SIGNUP_USING_MOBILE_NUMBER_SUCCESS =
  "SIGNUP_USING_MOBILE_NUMBER_SUCCESS";
export const SIGNUP_USING_MOBILE_NUMBER_ERROR =
  "SIGNUP_USING_MOBILE_NUMBER_ERROR";
//Otp verification using email id details actions
export const VERIFY_OTP_USING_EMAILID_START = "VERIFY_OTP_USING_EMAILID_START";
export const VERIFY_OTP_USING_EMAILID_SUCCESS =
  "VERIFY_OTP_USING_EMAILID_SUCCESS";
export const VERIFY_OTP_USING_EMAILID_ERROR = "VERIFY_OTP_USING_EMAILID_ERROR";
// verifiOTP_cation using mobile number details actions
export const VERIFY_OTP_USING_MOBILE_NUMBER_START =
  "VERIFY_OTP_USING_MOBILE_NUMBER_START";
export const VERIFY_OTP_USING_MOBILE_NUMBER_SUCCESS =
  "VERIFY_OTP_USING_MOBILE_NUMBER_SUCCESS";
export const VERIFY_OTP_USING_MOBILE_NUMBER_ERROR =
  "VERIFY_OTP_USING_MOBILE_NUMBER_ERROR";
// verifiOTP_cation using mobile number details actions
export const VERIFY_OTP_NEW_PASSWORD_START = "VERIFY_OTP_NEW_PASSWORD_START";
export const VERIFY_OTP_NEW_PASSWORD_SUCCESS =
  "VERIFY_OTP_NEW_PASSWORD_SUCCESS";
export const VERIFY_OTP_NEW_PASSWORD_ERROR = "VERIFY_OTP_NEW_PASSWORD_ERROR";
// resend OTP details actions
export const CREATE_RESEND_OTP_START = "CREATE_RESEND_OTP_START";
export const CREATE_RESEND_OTP_SUCCESS = "CREATE_RESEND_OTP_SUCCESS";
export const CREATE_RESEND_OTP_ERROR = "CREATE_RESEND_OTP_ERROR";
// create password recovery details
export const CREATE_PASSWORD_RECOVERY_START = "CREATE_PASSWORD_RECOVERY_START";
export const CREATE_PASSWORD_RECOVERY_SUCCESS =
  "CREATE_PASSWORD_RECOVERY_SUCCESS";
export const CREATE_PASSWORD_RECOVERY_ERROR = "CREATE_PASSWORD_RECOVERY_ERROR";

// create new password recovery details
export const CREATE_NEW_PASSWORD_START = "CREATE_NEW_PASSWORD_START";
export const CREATE_NEW_PASSWORD_SUCCESS = "CREATE_NEW_PASSWORD_SUCCESS";
export const CREATE_NEW_PASSWORD_ERROR = "CREATE_NEW_PASSWORD_ERROR";

// update new password recovery details
export const UPDATE_PASSWORD_START = "UPDATE_PASSWORD_START";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";
//Login using email id details actions
export const LOGIN_WITH_EMAILID_START = "LOGIN_WITH_EMAILID_START";
export const LOGIN_WITH_EMAILID_SUCCESS = "LOGIN_WITH_EMAILID_SUCCESS";
export const LOGIN_WITH_EMAILID_ERROR = "LOGIN_WITH_EMAILID_ERROR";
// Login using mobile number details actions
export const LOGIN_WITH_MOBILE_NUMBER_START = "LOGIN_WITH_MOBILE_NUMBER_START";
export const LOGIN_WITH_MOBILE_NUMBER_SUCCESS =
  "LOGIN_WITH_MOBILE_NUMBER_SUCCESS";
export const LOGIN_WITH_MOBILE_NUMBER_ERROR = "LOGIN_WITH_MOBILE_NUMBER_ERROR";
//create a new user
export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const LOAD_USER_START = "LOAD_USER_START";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
//home page component actions ...
export const LOAD_HOME_CAROUSELDATA_START = "LOAD_HOME_CAROUSELDATA_START";
export const LOAD_HOME_CAROUSELDATA_SUCCESS = "LOAD_HOME_CAROUSELDATA_SUCCESS";
export const LOAD_HOME_CAROUSELDATA_ERROR = "LOAD_HOME_CAROUSELDATA_ERROR";

export const LOAD_HOME_GRAND_GLOBAL_DATA_START =
  "LOAD_HOME_GRAND_GLOBAL_DATA_START";
export const LOAD_HOME_GRAND_GLOBAL_DATA_SUCCESS =
  "LOAD_HOME_GRAND_GLOBAL_DATA_SUCCESS";
export const LOAD_HOME_GRAND_GLOBAL_DATA_ERROR =
  "LOAD_HOME_GRAND_GLOBAL_DATA_ERROR";

export const LOAD_HOME_SHOP_CATEGORY_DATA_START =
  "LOAD_HOME_SHOP_CATEGORY_DATA_START";
export const LOAD_HOME_SHOP_CATEGORY_DATA_SUCCESS =
  "LOAD_HOME_SHOP_CATEGORY_DATA_SUCCESS";
export const LOAD_HOME_SHOP_CATEGORY_DATA_ERROR =
  "LOAD_HOME_SHOP_CATEGORY_DATA_ERROR";

export const LOAD_HOME_YOUMAYLIKE_DATA_START =
  "LOAD_HOME_YOUMAYLIKE_DATA_START";
export const LOAD_HOME_YOUMAYLIKE_DATA_SUCCESS =
  "LOAD_HOME_YOUMAYLIKE_DATA_SUCCESS";
export const LOAD_HOME_YOUMAYLIKE_DATA_ERROR =
  "LOAD_HOME_YOUMAYLIKE_DATA_ERROR";

export const LOAD_HOME_DISCOUNT_CARDS_DATA_START =
  "LOAD_HOME_DISCOUNT_CARDS_DATA_START";
export const LOAD_HOME_DISCOUNT_CARDS_DATA_SUCCESS =
  "LOAD_HOME_DISCOUNT_CARDS_DATA_SUCCESS";
export const LOAD_HOME_DISCOUNT_CARDS_DATA_ERROR =
  "LOAD_HOME_DISCOUNT_CARDS_DATA_ERROR";

export const LOAD_HOME_TODAY_DEALS_DATA_START =
  "LOAD_HOME_TODAY_DEALS_DATA_START";
export const LOAD_HOME_TODAY_DEALS_DATA_SUCCESS =
  "LOAD_HOME_TODAY_DEALS_DATA_SUCCESS";
export const LOAD_HOME_TODAY_DEALS_DATA_ERROR =
  "LOAD_HOME_TODAY_DEALS_DATA_ERROR";

// homepage action types for reusablity
export const LOAD_HOME_CAROUSEL_DATA = "LOAD_HOME_CAROUSEL_DATA";

// Product page actions
export const LOAD_PRODUCT_START = "LOAD_PRODUCT_START";
export const LOAD_PRODUCT_SUCCESS = "LOAD_PRODUCT_SUCCESS";
export const LOAD_PRODUCT_ERROR = "LOAD_PRODUCT_ERROR";

// Inner product page actions
export const LOAD_INNER_PRODUCT_START = "LOAD_INNER_PRODUCT_START";
export const LOAD_INNER_PRODUCT_SUCCESS = "LOAD_INNER_PRODUCT_SUCCESS";
export const LOAD_INNER_PRODUCT_ERROR = "LOAD_INNER_PRODUCT_ERROR";

// wishlist actions

export const CREATE_WISHLIST_PRODUCT_START = "CREATE_WISHLIST_PRODUCT_START";
export const CREATE_WISHLIST_PRODUCT_SUCCESS =
  "CREATE_WISHLIST_PRODUCT_SUCCESS";
export const CREATE_WISHLIST_PRODUCT_ERROR = "CREATE_WISHLIST_PRODUCT_ERROR";

export const LOAD_WISHLIST_PRODUCT_START = "LOAD_WISHLIST_PRODUCT_START";
export const LOAD_WISHLIST_PRODUCT_SUCCESS = "LOAD_WISHLIST_PRODUCT_SUCCESS";
export const LOAD_WISHLIST_PRODUCT_ERROR = "LOAD_WISHLIST_PRODUCT_ERROR";

export const DELETE_WISHLIST_PRODUCT_START = "DELETE_WISHLIST_PRODUCT_START";
export const DELETE_WISHLIST_PRODUCT_SUCCESS =
  "DELETE_WISHLIST_PRODUCT_SUCCESS";
export const DELETE_WISHLIST_PRODUCT_ERROR = "DELETE_WISHLIST_PRODUCT_ERROR";

// add to cart actions

export const CREATE_ADD_PRODUCT_TO_CART_START =
  "CREATE_ADD_PRODUCT_TO_CART_START";
export const CREATE_ADD_PRODUCT_TO_CART_SUCCESS =
  "CREATE_ADD_PRODUCT_TO_CART_SUCCESS";
export const CREATE_ADD_PRODUCT_TO_CART_ERROR =
  "CREATE_ADD_PRODUCT_TO_CART_ERROR";

export const LOAD_ADD_PRODUCT_TO_CART_START = "LOAD_ADD_PRODUCT_TO_CART_START";
export const LOAD_ADD_PRODUCT_TO_CART_SUCCESS =
  "LOAD_ADD_PRODUCT_TO_CART_SUCCESS";
export const LOAD_ADD_PRODUCT_TO_CART_ERROR = "LOAD_ADD_PRODUCT_TO_CART_ERROR";

export const DELETE_ADD_PRODUCT_TO_CART_START =
  "DELETE_ADD_PRODUCT_TO_CART_START";
export const DELETE_ADD_PRODUCT_TO_CART_SUCCESS =
  "DELETE_ADD_PRODUCT_TO_CART_SUCCESS";
export const DELETE_ADD_PRODUCT_TO_CART_ERROR =
  "DELETE_ADD_PRODUCT_TO_CART_ERROR";

// save for it later actions

export const CREATE_SAVE_PRODUCT_FOR_LATER_START =
  "CREATE_SAVE_PRODUCT_FOR_LATER_START";
export const CREATE_SAVE_PRODUCT_FOR_LATER_SUCCESS =
  "CREATE_SAVE_PRODUCT_FOR_LATER_SUCCESS";
export const CREATE_SAVE_PRODUCT_FOR_LATER_ERROR =
  "CREATE_SAVE_PRODUCT_FOR_LATER_ERROR";

export const LOAD_SAVE_PRODUCT_FOR_LATER_START =
  "LOAD_SAVE_PRODUCT_FOR_LATER_START";
export const LOAD_SAVE_PRODUCT_FOR_LATER_SUCCESS =
  "LOAD_SAVE_PRODUCT_FOR_LATER_SUCCESS";
export const LOAD_SAVE_PRODUCT_FOR_LATER_ERROR =
  "LOAD_SAVE_PRODUCT_FOR_LATER_ERROR";

export const DELETE_SAVE_PRODUCT_FOR_LATER_START =
  "DELETE_SAVE_PRODUCT_FOR_LATER_START";
export const DELETE_SAVE_PRODUCT_FOR_LATER_SUCCESS =
  "DELETE_SAVE_PRODUCT_FOR_LATER_SUCCESS";
export const DELETE_SAVE_PRODUCT_FOR_LATER_ERROR =
  "DELETE_SAVE_PRODUCT_FOR_LATER_ERROR";

// move to cart from save for it later actions

export const CREATE_PRODUCT_MOVETOCART_FROM_SAVE_FOR_LATER_START =
  "CREATE_PRODUCT_MOVETOCART_FROM_SAVE_FOR_LATER_START";
export const CREATE_PRODUCT_MOVETOCART_FROM_SAVE_FOR_LATER_SUCCESS =
  "CREATE_PRODUCT_MOVETOCART_FROM_SAVE_FOR_LATER_SUCCESS";
export const CREATE_PRODUCT_MOVETOCART_FROM_SAVE_FOR_LATER_ERROR =
  "CREATE_PRODUCT_MOVETOCART_FROM_SAVE_FOR_LATER_ERROR";

// order details page
export const CREATE_ORDER_DETAILS_START = "CREATE_ORDER_DETAILS_START";
export const CREATE_ORDER_DETAILS_SUCCESS = "CREATE_ORDER_DETAILS_SUCCESS";
export const CREATE_ORDER_DETAILS_ERROR = "CREATE_ORDER_DETAILS_ERROR";

export const LOAD_ORDER_DETAILS_START = "LOAD_ORDER_DETAILS_START";
export const LOAD_ORDER_DETAILS_SUCCESS = "LOAD_ORDER_DETAILS_SUCCESS";
export const LOAD_ORDER_DETAILS_ERROR = "LOAD_ORDER_DETAILS_ERROR";

export const REMOVE_ORDER_DETAILS_START = "REMOVE_ORDER_DETAILS_START";
export const REMOVE_ORDER_DETAILS_SUCCESS = "REMOVE_ORDER_DETAILS_SUCCESS";
export const REMOVE_ORDER_DETAILS_ERROR = "REMOVE_ORDER_DETAILS_ERROR";

// user address details
export const CREATE_USER_ADDRESS_START = "CREATE_USER_ADDRESS_START";
export const CREATE_USER_ADDRESS_SUCCESS = "CREATE_USER_ADDRESS_SUCCESS";
export const CREATE_USER_ADDRESS_ERROR = "CREATE_USER_ADDRESS_ERROR";

export const LOAD_USER_ADDRESS_START = "LOAD_USER_ADDRESS_START";
export const LOAD_USER_ADDRESS_SUCCESS = "LOAD_USER_ADDRESS_SUCCESS";
export const LOAD_USER_ADDRESS_ERROR = "LOAD_USER_ADDRESS_ERROR";

export const UPDATE_USER_ADDRESS_START = "UPDATE_USER_ADDRESS_START";
export const UPDATE_USER_ADDRESS_SUCCESS = "UPDATE_USER_ADDRESS_SUCCESS";
export const UPDATE_USER_ADDRESS_ERROR = "UPDATE_USER_ADDRESS_ERROR";

export const DELETE_USER_ADDRESS_START = "DELETE_USER_ADDRESS_START";
export const DELETE_USER_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_SUCCESS";
export const DELETE_USER_ADDRESS_ERROR = "DELETE_USER_ADDRESS_ERROR";

// Terms and conditions
export const LOAD_TERMS_CONDITIONS_START = "LOAD_TERMS_CONDITIONS_START";
export const LOAD_TERMS_CONDITIONS_SUCCESS = "LOAD_TERMS_CONDITIONS_SUCCESS";
export const LOAD_TERMS_CONDITIONS_ERROR = "LOAD_TERMS_CONDITIONS_ERROR";

// privacy policy
export const LOAD_PRIVACY_POLICY_START = "LOAD_PRIVACY_POLICY_START";
export const LOAD_PRIVACY_POLICY_SUCCESS = "LOAD_PRIVACY_POLICY_SUCCESS";
export const LOAD_PRIVACY_POLICY_ERROR = "LOAD_PRIVACY_POLICY_ERROR";

// about us
export const LOAD_ABOUT_US_START = "LOAD_ABOUT_US_START";
export const LOAD_ABOUT_US_SUCCESS = "LOAD_ABOUT_US_SUCCESS";
export const LOAD_ABOUT_US_ERROR = "LOAD_ABOUT_US_ERROR";



// notifcations preferences

export const LOAD_NOTIFICATION_PREFERENCES_START =
  "LOAD_NOTIFICATION_PREFERENCES_START";
export const LOAD_NOTIFICATION_PREFERENCES_SUCCESS =
  "LOAD_NOTIFICATION_PREFERENCES_SUCCESS";
export const LOAD_NOTIFICATION_PREFERENCES_ERROR =
  "LOAD_NOTIFICATION_PREFERENCES_ERROR";

export const UPDATE_NOTIFICATION_PREFERENCES_START =
  "UPDATE_NOTIFICATION_PREFERENCES_START";
export const UPDATE_NOTIFICATION_PREFERENCES_SUCCESS =
  "UPDATE_NOTIFICATION_PREFERENCES_SUCCESS";
export const UPDATE_NOTIFICATION_PREFERENCES_ERROR =
  "UPDATE_NOTIFICATION_PREFERENCES_ERROR";

// get orgerdetails in checkout page
export const CREATE_ORDERS_IN_CHECKOUT_START =
  "CREATE_ORDERS_IN_CHECKOUT_START";
export const CREATE_ORDERS_IN_CHECKOUT_SUCCESS =
  "CREATE_ORDERS_IN_CHECKOUT_SUCCESS";
export const CREATE_ORDERS_IN_CHECKOUT_ERROR =
  "CREATE_ORDERS_IN_CHECKOUT_ERROR";

export const LOAD_ORDERS_IN_CHECKOUT_START = "LOAD_ORDERS_IN_CHECKOUT_START";
export const LOAD_ORDERS_IN_CHECKOUT_SUCCESS =
  "LOAD_ORDERS_IN_CHECKOUT_SUCCESS";
export const LOAD_ORDERS_IN_CHECKOUT_ERROR = "LOAD_ORDERS_IN_CHECKOUT_ERROR";

// payment success with cod
export const CREATE_PAYMENT_COD_START = "CREATE_PAYMENT_COD_START";
export const CREATE_PAYMENT_COD_SUCCESS = "CREATE_PAYMENT_COD_SUCCESS";
export const CREATE_PAYMENT_COD_ERROR = "CREATE_PAYMENT_COD_ERROR";

export const LOAD_PAYMENT_COD_START = "LOAD_PAYMENT_COD_START";
export const LOAD_PAYMENT_COD_SUCCESS = "LOAD_PAYMENT_COD_SUCCESS";
export const LOAD_PAYMENT_COD_ERROR = "LOAD_PAYMENT_COD_ERROR";

// payment success with cod
export const CREATE_TRANSACTION_START = "CREATE_TRANSACTION_START";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_ERROR = "CREATE_TRANSACTION_ERROR";

// creating FCM token to backend
export const CREATE_FCM_TOKEN_START = "CREATE_FCM_TOKEN_START";
export const CREATE_FCM_TOKEN_SUCCESS = "CREATE_FCM_TOKEN_SUCCESS";
export const CREATE_FCM_TOKEN_ERROR = "CREATE_FCM_TOKEN_ERROR";

// notifcations
export const LOAD_NOTIFICATIONS_START = "LOAD_NOTIFICATIONS_START";
export const LOAD_NOTIFICATIONS_SUCCESS = "LOAD_NOTIFICATIONS_SUCCESS";
export const LOAD_NOTIFICATIONS_ERROR = "LOAD_NOTIFICATIONS_ERROR";

// creating invoice
export const CREATE_INVOICE_START = "CREATE_INVOICE_START";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const CREATE_INVOICE_ERROR = "CREATE_INVOICE_ERROR";

export const LOAD_INVOICE_START = "LOAD_INVOICE_START";
export const LOAD_INVOICE_SUCCESS = "LOAD_INVOICE_SUCCESS";
export const LOAD_INVOICE_ERROR = "LOAD_INVOICE_ERROR";